method: system
prompt: null

per_turn_prompts:
  - name: first_turn
    condition: "current_turn == 0"
    history_mode: all
    skip_env: 0.0
    response_truncation: python_code, answer_code
    template_dir: cuda_templates/first_turn
  - name: tool_response
    condition: "make_up_tool_response == True"
    history_mode: all
    skip_env: 0.0
    response_truncation: python_code, answer_code
    update_memory: false
    template_dir: cuda_templates/tool_response
