#!/bin/bash

VLLM018_PATH="${VLLM018_PATH:-/nfs/FM/chenshuailin/projects/kernel_agents/KernelGYM-vllm018}"
VENV="${VENV:-${VLLM018_PATH}/.venv-vllm0180}"

HEAD_NODE="${HEAD_NODE:-192.168.16.18}"
HEAD_PORT="${HEAD_PORT:-20629}"
WORKER_NODE="${WORKER_NODE:-192.168.16.24}"
WORKER_PORT="${WORKER_PORT:-14218}"
RAY_HEAD_PORT="${RAY_HEAD_PORT:-6379}"

TRAIN_HEAD_MODE="${TRAIN_HEAD_MODE:-ssh}"
TRAIN_HEAD_SSH_TARGET="${TRAIN_HEAD_SSH_TARGET:-root@${HEAD_NODE}}"
TRAIN_HEAD_CONTAINER="${TRAIN_HEAD_CONTAINER:-}"

TRAIN_WORKER_MODE="${TRAIN_WORKER_MODE:-ssh}"
TRAIN_WORKER_SSH_TARGET="${TRAIN_WORKER_SSH_TARGET:-root@${WORKER_NODE}}"
TRAIN_WORKER_CONTAINER="${TRAIN_WORKER_CONTAINER:-}"

TRAIN_SOCKET_IFNAME="${TRAIN_SOCKET_IFNAME:-ens22f0}"
TRAIN_GLOO_SOCKET_IFNAME="${TRAIN_GLOO_SOCKET_IFNAME:-${TRAIN_SOCKET_IFNAME}}"
TRAIN_NCCL_SOCKET_IFNAME="${TRAIN_NCCL_SOCKET_IFNAME:-${TRAIN_SOCKET_IFNAME}}"
TRAIN_NCCL_IB_DISABLE="${TRAIN_NCCL_IB_DISABLE:-1}"
TRAIN_NCCL_NET="${TRAIN_NCCL_NET:-Socket}"
TRAIN_NCCL_SOCKET_FAMILY="${TRAIN_NCCL_SOCKET_FAMILY:-AF_INET}"
TRAIN_NCCL_DEBUG="${TRAIN_NCCL_DEBUG:-WARN}"
TRAIN_NCCL_IB_HCA="${TRAIN_NCCL_IB_HCA:-}"
