#!/bin/bash

VLLM018_PATH="${VLLM018_PATH:-/data3/csl/projects/kernel_agents/KernelGYM-vllm018}"
VENV="${VENV:-${VLLM018_PATH}/.venv-vllm0180}"

HEAD_NODE="${HEAD_NODE:-10.0.18.3}"
HEAD_PORT="${HEAD_PORT:-22}"
WORKER_NODE="${WORKER_NODE:-10.0.18.5}"
WORKER_PORT="${WORKER_PORT:-22}"
RAY_HEAD_PORT="${RAY_HEAD_PORT:-6379}"

TRAIN_HEAD_MODE="${TRAIN_HEAD_MODE:-local}"
TRAIN_HEAD_SSH_TARGET="${TRAIN_HEAD_SSH_TARGET:-root@${HEAD_NODE}}"
TRAIN_HEAD_CONTAINER="${TRAIN_HEAD_CONTAINER:-}"

TRAIN_WORKER_MODE="${TRAIN_WORKER_MODE:-ssh-docker}"
TRAIN_WORKER_SSH_TARGET="${TRAIN_WORKER_SSH_TARGET:-node5}"
TRAIN_WORKER_CONTAINER="${TRAIN_WORKER_CONTAINER:-csl_verl}"

TRAIN_SOCKET_IFNAME="${TRAIN_SOCKET_IFNAME:-bond0}"
TRAIN_GLOO_SOCKET_IFNAME="${TRAIN_GLOO_SOCKET_IFNAME:-${TRAIN_SOCKET_IFNAME}}"
TRAIN_NCCL_SOCKET_IFNAME="${TRAIN_NCCL_SOCKET_IFNAME:-${TRAIN_SOCKET_IFNAME}}"
TRAIN_NCCL_IB_DISABLE="${TRAIN_NCCL_IB_DISABLE:-0}"
TRAIN_NCCL_NET="${TRAIN_NCCL_NET:-}"
TRAIN_NCCL_SOCKET_FAMILY="${TRAIN_NCCL_SOCKET_FAMILY:-AF_INET}"
TRAIN_NCCL_DEBUG="${TRAIN_NCCL_DEBUG:-WARN}"
TRAIN_NCCL_IB_HCA="${TRAIN_NCCL_IB_HCA:-}"
