hydra:
  searchpath:
    - file://verl_patch/trainer/code/config

defaults:
  - kernel_trainer_core
  - _self_

reward_model:
  kernel_backend: "cuda_agent"
  task_timeout: 30

actor_rollout_ref:
  rollout:
    engine_kwargs:
      vllm:
        language_model_only: true
    multi_turn:
      prompt_config_path: kernel/config/prompt_config/multi_turn_cuda_kernel.yaml
